// GLBasicLib_glu.h
// Copyright (C) Thomas Mulgrew (tmulgrew@slingshot.co.nz)// Generated by GLBasic header scanner
// From C:\Program Files\Borland\CBuilder6\Include\Gl\glu.h

#ifndef _GLBasicLib_glu_h
#define _GLBasicLib_glu_h
#include "../Compiler/TomComp.h"
#include "../VM/TomVM.h"

// Registration function
void InitGLBasicLib_glu(TomBasicCompiler& comp);
#endif
